// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrosCTe.API.Persistance;

#nullable disable

namespace RegistrosCTe.Infra.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistrosCTe.Domain.Entities.CTe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Aliquota")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("ValorCTe")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorICMS")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ViagemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ViagemId")
                        .IsUnique();

                    b.ToTable("CTe");
                });

            modelBuilder.Entity("RegistrosCTe.Domain.Entities.Carga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.ToTable("Carga");
                });

            modelBuilder.Entity("RegistrosCTe.Domain.Entities.DespesaAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ViagemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ViagemId");

                    b.ToTable("DespesasAdicionais");
                });

            modelBuilder.Entity("RegistrosCTe.Domain.Entities.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Distancia")
                        .HasColumnType("decimal(10,3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CargaId")
                        .IsUnique();

                    b.ToTable("Viagems");
                });

            modelBuilder.Entity("RegistrosCTe.Domain.Entities.CTe", b =>
                {
                    b.HasOne("RegistrosCTe.Domain.Entities.Viagem", "Viagem")
                        .WithOne("CTe")
                        .HasForeignKey("RegistrosCTe.Domain.Entities.CTe", "ViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("RegistrosCTe.Domain.Entities.DespesaAdicional", b =>
                {
                    b.HasOne("RegistrosCTe.Domain.Entities.Viagem", "Viagem")
                        .WithMany("DespesaAdicionais")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("RegistrosCTe.Domain.Entities.Viagem", b =>
                {
                    b.HasOne("RegistrosCTe.Domain.Entities.Carga", "Carga")
                        .WithOne("Viagem")
                        .HasForeignKey("RegistrosCTe.Domain.Entities.Viagem", "CargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carga");
                });

            modelBuilder.Entity("RegistrosCTe.Domain.Entities.Carga", b =>
                {
                    b.Navigation("Viagem")
                        .IsRequired();
                });

            modelBuilder.Entity("RegistrosCTe.Domain.Entities.Viagem", b =>
                {
                    b.Navigation("CTe")
                        .IsRequired();

                    b.Navigation("DespesaAdicionais");
                });
#pragma warning restore 612, 618
        }
    }
}
