<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RegistrosCTe.Domain\RegistrosCTe.Domain.csproj" />
    <ProjectReference Include="..\RegistrosCTe.Infra\RegistrosCTe.Infra.csproj" />
  </ItemGroup>

</Project>
